import { ref, watch, onMounted } from 'vue';
import { useStorage } from '@vueuse/core'

const translations = {
    lv: {
        greet: 'Čau!',
        theme_mode: 'Tumšais režīms',
        home: 'Sākums',
        home_content: 'long content',
        about: 'Par mani',
        about_content: 'long_descr',
        road: 'Ceļš',
        descr_2001: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna',
        descr_2002: 'Neatceros kas te notika',
        descr_2003: 'Vēljoprojām neatceros',
        descr_2004: 'Iespējams sāku iet bērnu dārzā',
        descr_2005: 'Neatceros',
        descr_2006: 'Šo šeit',
        descr_2007: 'Laikam sāku iet skolā, es neatceros',
        descr_2008: 'Es neatceros',
        descr_2009: 'Pazuda atmiņa',
        descr_2010: 'Nekā interesanta',
        descr_2011: 'Hmmm, jāpadomā',
        descr_2012: 'Es piedzimu',
        descr_2013: 'Es piedzimu',
        descr_2014: 'Es piedzimu',
        descr_2015: 'Es piedzimu',
        descr_2016: 'Es piedzimu',
        descr_2017: 'Es piedzimu',
        descr_2018: 'Es piedzimu',
        descr_2019: 'Es piedzimu',
        descr_2020: 'Es piedzimu',
        descr_2021: 'Es piedzimu',
        descr_2022: 'Es piedzimu',
        descr_2023: 'Es piedzimu',
        descr_2024: 'Es piedzimu',
        long_descr_2001: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
        long_descr_2002: 'Es piedzimu',
        long_descr_2003: 'Es piedzimu',
        long_descr_2004: 'Es piedzimu',
        long_descr_2005: 'Es piedzimu',
        long_descr_2006: 'Es piedzimu',
        long_descr_2007: 'Es piedzimu',
        long_descr_2008: 'Es piedzimu',
        long_descr_2009: 'Es piedzimu',
        long_descr_2010: 'Es piedzimu',
        long_descr_2011: 'Es piedzimu',
        long_descr_2012: 'Es piedzimu',
        long_descr_2013: 'Es piedzimu',
        long_descr_2014: 'Es piedzimu',
        long_descr_2015: 'Es piedzimu',
        long_descr_2016: 'Es piedzimu',
        long_descr_2017: 'Es piedzimu',
        long_descr_2018: 'Es piedzimu',
        long_descr_2019: 'Es piedzimu',
        long_descr_2020: 'Es piedzimu',
        long_descr_2021: 'Es piedzimu',
        long_descr_2022: 'Es piedzimu',
        long_descr_2023: 'Es piedzimu',
        long_descr_2024: 'Es piedzimu',
        lorem_short: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna',
        lorem_long: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',

    },
    en: {
        greet: 'Hey!',
        theme_mode: 'Dark Mode',
        home: 'Home',
        home_content: 'long content',
        about: 'About me',
        about_content: 'long_descr',
        road: 'Road',
        descr_2001: 'I was born',
        descr_2002: 'Es piedzimu',
        descr_2003: 'Es piedzimu',
        descr_2004: 'Es piedzimu',
        descr_2005: 'Es piedzimu',
        descr_2006: 'Es piedzimu',
        descr_2007: 'Es piedzimu',
        descr_2008: 'Es piedzimu',
        descr_2009: 'Es piedzimu',
        descr_2010: 'Es piedzimu',
        descr_2011: 'Es piedzimu',
        descr_2012: 'Es piedzimu',
        descr_2013: 'Es piedzimu',
        descr_2014: 'Es piedzimu',
        descr_2015: 'Es piedzimu',
        descr_2016: 'Es piedzimu',
        descr_2017: 'Es piedzimu',
        descr_2018: 'Es piedzimu',
        descr_2019: 'Es piedzimu',
        descr_2020: 'Es piedzimu',
        descr_2021: 'Es piedzimu',
        descr_2022: 'Es piedzimu',
        descr_2023: 'Es piedzimu',
        descr_2024: 'Es piedzimu',
        long_descr_2001: 'I was born',
        long_descr_2002: 'Es piedzimu',
        long_descr_2003: 'Es piedzimu',
        long_descr_2004: 'Es piedzimu',
        long_descr_2005: 'Es piedzimu',
        long_descr_2006: 'Es piedzimu',
        long_descr_2007: 'Es piedzimu',
        long_descr_2008: 'Es piedzimu',
        long_descr_2009: 'Es piedzimu',
        long_descr_2010: 'Es piedzimu',
        long_descr_2011: 'Es piedzimu',
        long_descr_2012: 'Es piedzimu',
        long_descr_2013: 'Es piedzimu',
        long_descr_2014: 'Es piedzimu',
        long_descr_2015: 'Es piedzimu',
        long_descr_2016: 'Es piedzimu',
        long_descr_2017: 'Es piedzimu',
        long_descr_2018: 'Es piedzimu',
        long_descr_2019: 'Es piedzimu',
        long_descr_2020: 'Es piedzimu',
        long_descr_2021: 'Es piedzimu',
        long_descr_2022: 'Es piedzimu',
        long_descr_2023: 'Es piedzimu',
        long_descr_2024: 'Es piedzimu',
    },
};

export function useTranslations() {
    const locale = useStorage('locale', 'lv');
    const currentTranslations = ref({});

    watch(locale, (newLocale) => {
        currentTranslations.value = translations[newLocale] || {};
    }, {immediate: true});

    const setLocale = (newLocale) => {
        locale.value = newLocale;
    };

    const translate = (key) => {
        return currentTranslations.value[key] || key;
    };

    return { translate, locale, setLocale };
}
